###Q.1 Create two 3*3 matrix, with random numbers. Perform following operations; 

a. Addition of both the mtrices 

b. Subtraction 

c. Multiplication of the matrices 

In [17]:
import numpy as np

A = np.random.randint(1, 10, size=(3, 3))
B = np.random.randint(1, 10, size=(3, 3))

In [ ]:
print("Matrix A:")
A


Matrix A:
[[1 6 3]
 [3 8 6]
 [4 2 2]]


In [22]:
"Matrix B:-"
print(B)

[[1 6 3]
 [3 8 6]
 [4 2 2]]


In [19]:
#1. Addition
addition = A + B
"Addition of A and B:-"
addition


array([[ 6, 15,  9],
       [ 8,  9, 15],
       [13,  3, 10]], dtype=int32)

In [20]:
#2. Substraction:-
subtraction = A - B
"Subtraction of A and B:"
subtraction

array([[ 4,  3,  3],
       [ 2, -7,  3],
       [ 5, -1,  6]], dtype=int32)

In [21]:
#Multiplication:-
multiplication = np.dot(A, B)
"Multiplication of A and B:-"
multiplication


array([[ 56, 114,  81],
       [ 44,  56,  39],
       [ 44,  78,  49]], dtype=int32)